Repository ViktoriyaRyazhska/Lv-658.TAQC, pull requests merged in 2021-12, with the labels that each got.

#85 The smallest
  src/tasks/GapPrimes.java
  src/tasks/TheSmallest.java
Labels: team3

#86 Added menu
  .gitignore
  tasks/MainMenu.java
Labels: team 2

#90 Completed task 'Trailing zeros in factorial'
  src/tasks/TrailingZeros.java
Labels: team3

#95 add task Build a pile of Cubes
  src/tasks/BuildCubes.java
Labels: team3

#96 Added task 'To square(root) or not to square(root)'
  src/tasks/SquareRoot.java
Labels: team3

#100 Count positive
  src/tasks/CountPositive.java
  src/tasks/SquareRoot.java
Labels: team3

#97 "SumOfTerm" task is done
  src/tasks/SumOfTerm.java
Labels: team3

#102 Miles to kilometers
  src/tasks/KeepHydrated.java
  src/tasks/MilesToKilometers.java
Labels: team3

#105 Bug fixed in task 'Miles to Kilometers'
  src/tasks/MilesToKilometers.java
Labels: team3

#106 Added task 'Convert a String to a Number'
  src/tasks/StringToNumber.java
Labels: team3

#109 Added task KeepHydrated
  src/main/tasks/KeepHydrated.java
Labels: team1

#112 add task BalanceChecking
  src/tasks/BalanceChecking.java
Labels: team3

#117 Bug fixed in task 'Miles to Km'
  src/tasks/MilesToKilometers.java
Labels: team3

#118 add RankingNBA task
  src/tasks/RankingNBA.java
Labels: team3

#121 add task Floating Point Approximation
  src/tasks/FloatingPoint.java
Labels: team3

#124 Adding exceptions
  src/tasks/CountPositive.java
  src/tasks/KeepHydrated.java
  src/tasks/MilesToKilometers.java
  src/tasks/SquareRoot.java
  src/tasks/StringToNumber.java
  src/tasks/VolumeCuboid.java
Labels: team3

#123 Completed task 'PerimetrSquares'
  src/tasks/PerimeterSquares.java
Labels: team3

#125 add tasks HelpBookseller and Rainfall
  src/tasks/HelpBookseller.java
  src/tasks/Rainfall.java
Labels: team3
